### ISSUE TITLE
[Issue] 'React' must be in scope when using JSX

### ISSUE THREAD

**Issue by minh197** [minh197/WeBlog#10]
Encountering issue `'React' must be in scope when using JSX` when launching the project
<img width="914" alt="Screenshot 2024-03-16 at 10 02 49 AM" src="https://github.com/minh197/WeBlog/assets/61608148/78b7f5c3-09ee-46e3-965c-8b2f4e6720c9">

**Comment by Moethantko** [comment]
Issue is already fixed by Minh.
